---
title: "multiclass_per_class_accuracy"
author: "Daniel Rawlinson"
date: "2024-05-02"
output: html_document
---

#Library
```{r}
library(pROC)
library(caret)
library(fmsb)
library(tidyr)
library(purrr)
library(wesanderson)
library(dplyr)
```

#Wasserstein function
```{r}
.diffs_all<-function(v,ty){
  m2=cbind(ty[-length(ty)], ty[-1])
  ty2 =apply(m2,1,function(v)v[2]+v[1])
  ty3 = ty2/sum(ty2)
  m1 = cbind(v[-length(v)], v[-1], ty3)
  sum(apply(m1,1,function(v2) (v2[1] - v2[2])*v2[3]))
}
```


#Data
```{r}
coin_fold_results_unweighted <- readRDS('output/RAPIDS_kfold_results_unweighted.Rds')
coin_fold_results_weighted <- readRDS('output/RAPIDS_kfold_results_weighted.Rds')
coin_data <- readRDS('input/coin_data/coin_multiclass_data.prepd.Rds')

alvez_fold_results_unweighted <- readRDS('output/alvez_kfold_results_unweighted.Rds')
alvez_fold_results_weighted <- readRDS('output/alvez_kfold_results_weighted.Rds')
alvez_data <- readRDS('input/alvez_data/alvez_data.prepd.Rds')

```

#RAPIDS analysis
```{r}
RAPIDS_results <- lapply(X = list(weighted = coin_fold_results_weighted, unweighted = coin_fold_results_unweighted), FUN = function(fold_results) {
  

num_features_list <- list()
cms <- list() #list to hold confusion matrix results
radarchart_data <- list()
was_objects <- list()

model_select = 'min' #or `1se`

for (method in names(fold_results[[1]])) {
model_min <- lapply( fold_results, function(x) x[[method]]$min)

fitted_class <- unlist(lapply(model_min, '[', 'fitted'))
true_class <- unlist(lapply(model_min, '[', 'true'))
fitted_probs <- lapply(model_min, function(x)  x$fitted_probs)


cm <- caret::confusionMatrix(fitted_class %>% factor(levels = c(2,0,1)), true_class %>% factor(levels = c(2,0,1)))
cms[[method]] <- cm

all_fitted_probs <- do.call(rbind, fitted_probs) %>% as.matrix()

auc_list <- list()
was_ggps <- list()
was_list <- list()

#per class auc
for (i in fold_results[[2]]$fspls[[model_select]]$model$levels) {
  
  faux_binary_class <- true_class
  case_idx <- faux_binary_class == i
  faux_binary_class[-case_idx] <- 0
  faux_binary_class[case_idx] <- 1
  
  auc_obj <- pROC::roc(faux_binary_class, as.numeric(all_fitted_probs[,i]), auc = T)
  auc_list[[i]] <- auc_obj$auc
  
  
  #wasserstein for class
  y = faux_binary_class
  yp2 = all_fitted_probs[,i]
  ty= table(y)  ## assumes ty is ordered, which it should be
  nmey = as.numeric(names(ty))
  range = c(nmey[1], nmey[length(nmey)])
  names(nmey) = nmey
  cdfs=lapply(nmey,function(yv){
    ecdf(yp2[y==yv])
  })
  kns = lapply(cdfs,  stats::knots)
  kn = unique(sort(unlist(kns)))
  matr0 = cbind(c(range[1],kn),c(kn,range[2]))
  midp = apply(matr0,1,mean)
  diffp = apply(matr0,1,function(v)v[2]-v[1])
  matr = as.matrix(data.frame(lapply(cdfs, function(cdf) cdf(midp))))
  
  dimnames(matr)[[2]] = names(cdfs)
  dimnames(matr)[[1]] = c(range[1], kn)
  matr_plot <- matr %>% as.data.frame %>% tibble::rownames_to_column(var = 'x') %>% tidyr::pivot_longer(cols = c('0','1')) %>% mutate(x = as.numeric(x))
  #print(matr)
  diff = apply(matr,1,function(v) .diffs_all(v, ty)) 
  was_list[[i]] <- c(NA,sum( diffp * diff),NA)
  was_ggps[[i]] <- ggplot(matr_plot, aes(x = x, y = value, color = name)) + geom_point(size = 0.5, stroke = NA) + 
    ggtitle(label = paste('prob cdf, method =', method, ', class =', i)) + 
    annotate('text', x = 0.00, y = 1.0, label = paste('diff =', round(was_list[[i]][2], 3)), size = 4*0.36, hjust = 0) +
    theme_minimal() +
    theme(text = element_text(size = 6), axis.title = element_blank()) + coord_cartesian(xlim= c(0,1))
  
}


auc_vals <- unlist(auc_list)
print(auc_vals)

radarchart_data[[method]] <- t(cbind(cm$byClass[,c('Sensitivity','Specificity')], auc_vals)) %>% as.data.frame() %>% mutate(method = method) %>% tibble::rownames_to_column(var = 'measure')


num_features_list[[method]] <- lapply(fold_results, function(x) x[[method]]$min$nfeatures) %>% unlist()

was_objects[[method]] <- list(plots = was_ggps, values = was_list)

}

return(list(was = was_objects, feats = num_features_list, radar = radarchart_data, cms = cms))

})

RAPIDS_radarchart_data_list <- lapply(RAPIDS_results, function(x) {do.call(rbind, x$radar) %>% tidyr::pivot_longer(cols = starts_with('Class')) })
RAPIDS_radarchart_data <- map_df(RAPIDS_radarchart_data_list, ~as.data.frame(.x), .id="type") %>% 
  mutate(name = factor(name, levels = c('Class: 2', 'Class: 0', 'Class: 1'))) 

```


#Alvez analysis
```{r}
alvez_results <- lapply(X = list(weighted = alvez_fold_results_weighted, unweighted = alvez_fold_results_unweighted), FUN = function(fold_results) {
  

num_features_list <- list()
cms <- list() #list to hold confusion matrix results
radarchart_data <- list()
was_objects <- list()

model_select = 'min' #or `1se`

for (method in names(fold_results[[1]])) {
model_min <- lapply( fold_results, function(x) x[[method]]$min)

fitted_class <- unlist(lapply(model_min, '[', 'fitted'))
true_class <- unlist(lapply(model_min, '[', 'true'))
fitted_probs <- lapply(model_min, function(x)  x$fitted_probs)


cm <- caret::confusionMatrix(fitted_class %>% factor(levels = c(2,0,1,3,4)), true_class %>% factor(levels = c(2,0,1,3,4)))
cms[[method]] <- cm

all_fitted_probs <- do.call(rbind, fitted_probs) %>% as.matrix()

auc_list <- list()
was_ggps <- list()
was_list <- list()

#per class auc
for (i in fold_results[[2]]$fspls[[model_select]]$model$levels) {
  
  faux_binary_class <- true_class
  case_idx <- faux_binary_class == i
  faux_binary_class[-case_idx] <- 0
  faux_binary_class[case_idx] <- 1
  
  auc_obj <- pROC::roc(faux_binary_class, as.numeric(all_fitted_probs[,i]), auc = T)
  auc_list[[i]] <- auc_obj$auc
  
  
  #wasserstein for class
  y = faux_binary_class
  yp2 = all_fitted_probs[,i]
  ty= table(y)  ## assumes ty is ordered, which it should be
  nmey = as.numeric(names(ty))
  range = c(nmey[1], nmey[length(nmey)])
  names(nmey) = nmey
  cdfs=lapply(nmey,function(yv){
    ecdf(yp2[y==yv])
  })
  kns = lapply(cdfs,  stats::knots)
  kn = unique(sort(unlist(kns)))
  matr0 = cbind(c(range[1],kn),c(kn,range[2]))
  midp = apply(matr0,1,mean)
  diffp = apply(matr0,1,function(v)v[2]-v[1])
  matr = as.matrix(data.frame(lapply(cdfs, function(cdf) cdf(midp))))
  
  dimnames(matr)[[2]] = names(cdfs)
  dimnames(matr)[[1]] = c(range[1], kn)
  matr_plot <- matr %>% as.data.frame %>% tibble::rownames_to_column(var = 'x') %>% tidyr::pivot_longer(cols = c('0','1')) %>% mutate(x = as.numeric(x))
  #print(matr)
  diff = apply(matr,1,function(v) .diffs_all(v, ty)) 
  was_list[[i]] <- c(NA,sum( diffp * diff),NA)
  was_ggps[[i]] <- ggplot(matr_plot, aes(x = x, y = value, color = name)) + geom_point(size = 0.5, stroke = NA) + 
    ggtitle(label = paste('prob cdf, method =', method, ', class =', i)) + 
    annotate('text', x = 0.00, y = 1.0, label = paste('diff =', round(was_list[[i]][2], 3)), size = 4*0.36, hjust = 0) +
    theme_minimal() +
    theme(text = element_text(size = 6), axis.title = element_blank()) + coord_cartesian(xlim= c(0,1))
  
}


auc_vals <- unlist(auc_list)
print(auc_vals)

radarchart_data[[method]] <- t(cbind(cm$byClass[,c('Sensitivity','Specificity')], auc_vals)) %>% as.data.frame() %>% mutate(method = method) %>% tibble::rownames_to_column(var = 'measure')


num_features_list[[method]] <- lapply(fold_results, function(x) x[[method]]$min$nfeatures) %>% unlist()

was_objects[[method]] <- list(plots = was_ggps, values = was_list)

}

return(list(was = was_objects, feats = num_features_list, radar = radarchart_data, cms = cms))

})



alvez_radarchart_data_list <- lapply(alvez_results, function(x) {do.call(rbind, x$radar) %>% tidyr::pivot_longer(cols = starts_with('Class')) })
alvez_radarchart_data <- map_df(alvez_radarchart_data_list, ~as.data.frame(.x), .id="type") %>% 
  mutate(name = factor(name, levels = c('Class: 2', 'Class: 0', 'Class: 1', 'Class: 3', 'Class: 4'))) #match order with confusion plots
```

#plot Alvez and RAPIDS per class
```{r}
data_for_class_auc_plot <- RAPIDS_radarchart_data %>% mutate(data = 'RAPIDS') %>% full_join(alvez_radarchart_data %>% mutate(data = 'Alvez')) %>% 
  mutate(measure = replace(measure, measure == 'auc_vals', 'AUC'))

measure_means <- data_for_class_auc_plot %>%
  group_by(data, type, method, measure) %>%
  summarize(means = mean(value),
            se = sd(value) / sqrt(n()),
            margin = 1.96 * se,
            upper = means + margin,
            lower = means - margin) %>% 
  mutate(upper = case_when(upper > 1  ~ 1, .default = upper))

ggplot(data_for_class_auc_plot) +
  geom_point(aes(x = method, y = value, color = name, shape= type, group = type), alpha = 0.6, position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1), size = 1.8) + 
  geom_errorbar(data = measure_means, mapping = aes(x = method, y = means, ymin = means, ymax = means, group = type), 
                linetype = 'dashed', color = 'black', position = position_dodge(0.6), width = 0.5) +
  facet_wrap(vars(data, measure), nrow = 2) + 
  scale_color_manual(values  = wes_palette('Darjeeling1')) + 
  scale_y_continuous(trans = 'exp') +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1), legend.position = 'bottom')

ggsave('plots/RAPIDS_and_Alvez_measure_plots_per_class.pdf', height = 8, width = 7)

```
#Plot RAPIDS and Alvez wasserstein plots
```{r}
all_diff_plots <- lapply(RAPIDS_results$unweighted$was, function(x) x$plots) %>% do.call(c, .)
p <- patchwork::wrap_plots(all_diff_plots, ncol = 3) + patchwork::plot_layout(guides = 'collect')
p <- p + theme(legend.position = 'none')
ggsave(p, filename = 'plots/unweighted_was_RAPIDS.pdf', width = 3.8, height = 4)

all_diff_plots <- lapply(RAPIDS_results$weighted$was, function(x) x$plots) %>% do.call(c, .)
p <- patchwork::wrap_plots(all_diff_plots, ncol = 3) + patchwork::plot_layout(guides = 'collect')
p <- p + theme(legend.position = 'none')
ggsave(p, filename = 'plots/weighted_was_RAPIDS.pdf', width = 3.8, height = 4)

all_diff_plots <- lapply(alvez_results$unweighted$was, function(x) x$plots) %>% do.call(c, .)
p <- patchwork::wrap_plots(all_diff_plots, ncol = 5) + patchwork::plot_layout(guides = 'collect')
p <- p + theme(legend.position = 'none')
ggsave(p, filename = 'plots/unweighted_was_Alvez.pdf', width = 3.8, height = 4)

all_diff_plots <- lapply(alvez_results$weighted$was, function(x) x$plots) %>% do.call(c, .)
p <- patchwork::wrap_plots(all_diff_plots, ncol = 5) + patchwork::plot_layout(guides = 'collect')
p <- p + theme(legend.position = 'none')
ggsave(p, filename = 'plots/weighted_was_Alvez.pdf', width = 3.8, height = 4)





#ggsave('weighted_prob_diffs_coin.pdf', width = 8.268, height = 9.5, units = 'in')
```


